# Generated by Django 5.2.1 on 2025-06-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_remove_asignacion_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año de fabricación del vehículo', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_chasis',
            field=models.CharField(blank=True, help_text='Número de chasis (VIN)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='numero_motor',
            field=models.CharField(blank=True, help_text='Número de motor', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='req_tipo_vehiculo_preferente',
            field=models.CharField(blank=True, choices=[('automovil', 'Automóvil/Funcionario'), ('station_wagon', 'Station Wagon'), ('minibus', 'Minibús'), ('camioneta_pickup', 'Camioneta Pickup'), ('camioneta_suv', 'Camioneta SUV/Grande Pasajeros'), ('furgon_insumos', 'Furgón para Insumos'), ('ambulancia', 'Ambulancia para Pacientes'), ('camion_carga', 'Camión de Carga Ligera'), ('otro', 'Otro')], help_text='Tipo de vehículo preferido/requerido (opcional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('automovil', 'Automóvil/Funcionario'), ('station_wagon', 'Station Wagon'), ('minibus', 'Minibús'), ('camioneta_pickup', 'Camioneta Pickup'), ('camioneta_suv', 'Camioneta SUV/Grande Pasajeros'), ('furgon_insumos', 'Furgón para Insumos'), ('ambulancia', 'Ambulancia para Pacientes'), ('camion_carga', 'Camión de Carga Ligera'), ('otro', 'Otro')], default='automovil', help_text='Tipo de vehículo según su uso principal', max_length=50),
        ),
    ]
