# Generated by Django 5.2.1 on 2025-06-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0003_vehiculo_anio_vehiculo_numero_chasis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='solicitante_jerarquia',
            field=models.IntegerField(choices=[(3, 'Jefatura/Subdirección'), (2, 'Coordinación/Referente'), (1, 'Funcionario'), (0, 'Otro/No especificado')], default=0, help_text='Nivel jerárquico del área o persona que origina la solicitud.'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='solicitante_nombre',
            field=models.CharField(blank=True, help_text='Nombre del funcionario responsable del traslado o contacto principal de la solicitud.', max_length=200),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='solicitante_telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del solicitante o responsable.', max_length=50),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='tipos_vehiculo_habilitados',
            field=models.CharField(blank=True, help_text='Tipos de vehículo que puede manejar (ej: automovil,furgon_insumos), separados por coma', max_length=255),
        ),
    ]
