# Generated by Django 5.2.1 on 2025-06-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0004_asignacion_solicitante_jerarquia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='req_carga_kg',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='capacidad_carga_kg',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='req_tipo_vehiculo_preferente',
            field=models.CharField(blank=True, choices=[('automovil', 'Automóvil/Funcionario'), ('camioneta_pickup', 'Camioneta Pickup'), ('camioneta_suv', 'Camioneta SUV/Grande Pasajeros'), ('furgon_insumos', 'Furgón para Insumos'), ('ambulancia', 'Ambulancia para Pacientes'), ('camion_carga', 'Camión de Carga Ligera'), ('otro', 'Otro')], help_text='Tipo de vehículo preferido/requerido (opcional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='estado_disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('dia_libre', 'Día Libre'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('automovil', 'Automóvil/Funcionario'), ('camioneta_pickup', 'Camioneta Pickup'), ('camioneta_suv', 'Camioneta SUV/Grande Pasajeros'), ('furgon_insumos', 'Furgón para Insumos'), ('ambulancia', 'Ambulancia para Pacientes'), ('camion_carga', 'Camión de Carga Ligera'), ('otro', 'Otro')], default='automovil', help_text='Tipo de vehículo según su uso principal', max_length=50),
        ),
    ]
