# Generated by Django 5.2.1 on 2025-06-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0005_remove_asignacion_req_carga_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='req_tipo_vehiculo_preferente',
            field=models.CharField(blank=True, choices=[('automovil', 'Automóvil'), ('camioneta', 'Camioneta'), ('minibus', 'Minibús'), ('station_wagon', 'Station Wagon')], help_text='Tipo de vehículo preferido/requerido (opcional)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='tipos_vehiculo_habilitados',
            field=models.CharField(blank=True, help_text='Tipos de vehículo que puede manejar (ej: automovil,camioneta), separados por coma', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('automovil', 'Automóvil'), ('camioneta', 'Camioneta'), ('minibus', 'Minibús'), ('station_wagon', 'Station Wagon')], default='automovil', help_text='Tipo de vehículo según su uso principal', max_length=50),
        ),
    ]
