# Generated by Django 5.2.1 on 2025-06-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0006_alter_asignacion_req_tipo_vehiculo_preferente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del conductor', null=True, upload_to='conductores_fotos/'),
        ),
    ]
