# Generated by Django 5.2.1 on 2025-06-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asignaciones", "0008_remove_vehiculo_ubicacion_actual_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacion",
            name="fecha_asignacion_funcionario",
            field=models.DateTimeField(
                blank=True,
                help_text="Marca temporal cuando un funcionario crea la asignación",
                null=True,
            ),
        ),
    ]
