# Generated by Django 5.2.1 on 2025-06-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0008_asignacion_solicitante_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='solicitante_usuario',
        ),
    ]
