# Generated by Django 5.2.1 on 2025-06-05 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0009_remove_asignacion_solicitante_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='solicitante_usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que realiza la solicitud (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante del Sistema'),
        ),
    ]
