# Generated by Django 5.2.1 on 2025-06-18 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0009_asignacion_fecha_asignacion_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de turno'), ('salida', 'Salida de turno')], max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_turno', to='asignaciones.conductor')),
            ],
            options={
                'verbose_name': 'Registro de Turno',
                'verbose_name_plural': 'Registros de Turno',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
