# Generated by Django 5.2.1 on 2025-06-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0010_registroturno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='estado_disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('dia_libre', 'Día Libre'), ('no_disponible', 'No Disponible')], default='dia_libre', max_length=20),
        ),
    ]
