# Generated by Django 5.2.1 on 2025-06-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0011_alter_conductor_estado_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='distancia_recorrida_km',
            field=models.FloatField(blank=True, help_text='Distancia del viaje en km.', null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.FloatField(default=0.0, help_text='Kilometraje total del vehículo en km.'),
        ),
    ]
