# Generated by Django 5.2.1 on 2025-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0012_asignacion_distancia_recorrida_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='responsable_nombre',
            field=models.CharField(blank=True, help_text='Nombre del responsable de la asignación.', max_length=200),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='responsable_telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del responsable de la asignación.', max_length=50),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='solicitante_nombre',
            field=models.CharField(blank=True, help_text='Nombre del solicitante de la asignación.', max_length=200),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='solicitante_telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del solicitante.', max_length=50),
        ),
    ]
