# Generated by Django 5.2.1 on 2025-07-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0013_asignacion_responsable_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='destino_descripcion',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_hora_fin_real',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='fecha_hora_solicitud',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='origen_descripcion',
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='req_caracteristicas_especiales',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='ubicacion_actual_lat',
        ),
        migrations.RemoveField(
            model_name='conductor',
            name='ubicacion_actual_lon',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='caracteristicas_adicionales',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='conductor_preferente',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='ubicacion',
        ),
    ]
