# Generated by Django 5.2.1 on 2025-07-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0014_remove_asignacion_destino_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='destino_descripcion',
            field=models.CharField(default='Destino pendiente', help_text='Descripción del destino', max_length=200),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='origen_descripcion',
            field=models.CharField(blank=True, help_text='Descripción del origen (opcional)', max_length=200),
        ),
    ]
