# Generated by Django 5.0.6 on 2025-07-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0015_asignacion_destino_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='run',
            field=models.CharField(blank=True, help_text='Rol Único Nacional (ej: 12345678-9)', max_length=12, null=True, unique=True),
        ),
    ]
